# parameters:
#   - name: users
#     type: object
#     default:
#       - john
#       - jane
#       - bob

# steps:
#   - ${{ each user in parameters.users }}:
#       displayName: 'Create user ${{ user }}'

trigger:
  batch: true
  branches:
    include:
      - develop

parameters:
  - name: environ
    type: object
    default:
      - uat
      - pro
        
    
      
  - name: RunADF
    displayName: Run ADF
    type: boolean
    default: true

variables:

  - name: ADFProjectPath
    value: '$(Build.Repository.LocalPath)/ADFIntegration'
  
  - name: ADFSourceFactoryPath
    value: '/subscriptions/1ead8068-fad9-4a3a-a6ca-8c1b51afc5d9/resourceGroups/daa-pract-adf-dev/providers/Microsoft.DataFactory/factories/daapractdevadf'

  #- #name: ADFRootFolder
    #value: '$(System.DefaultWorkingDirectory)'

stages:

  - stage: CI
    jobs: 

    - template: release_template/ADF-Build.yml
      parameters:
        projectPath: ${{ variables.ADFProjectPath }}
        rootFolder: ${{ variables.ADFRootFolder }}
        sourceFactoryPath: ${{ variables.ADFSourceFactoryPath }}
        enabled: ${{ parameters.RunADF }}
  
  - ${{ each env in parameters.environ }}:
    - stage: ${{ env.name }}
      displayName: 'Deploy to ${{ env.name }}'
      variables:
        - group: ${{ env }}
        - name: connection
          ${{ if eq(env, 'qa') }}:
            value: 'Microsoft Azure Enterprise BigDataAI (1ead8068-fad9-4a3a-a6ca-8c1b51afc5d9)'
          ${{ if eq(env, 'prod') }}:
            value: 'Microsoft Azure Enterprise BigDataAI (1ead8068-fad9-4a3a-a6ca-8c1b51afc5d9)'
        - name: adfresourcegroup
          ${{ if eq(env, 'qa') }}:
            value: $(adfqaResourceGroup)
          ${{ if eq(env, 'prod') }}:
            value: $(adfprodResourceGroup)
        - name: adfName
          ${{ if eq(env, 'qa') }}:
            value: $(adfqaname)
          ${{ if eq(env, 'prod') }}:
            value: $(adfprodname)

      jobs:
        - template: release_template/ADF-Release.yml
          parameters:
            env: ${{ env }}
            azureServiceConnection: ${{ variables['connection'] }}
            azureSubscriptionId: $(subscriptionId)
            azureLocation: $(adfLocation)
            azureResourceGroup: ${{ variables['adfresourcegroup'] }}
            adfName: ${{ variables['adfName'] }}
            enabled: ${{ parameters.RunADF }}







