trigger:
- main 

pool:
  vmImage: 'windows-latest'
# Installs Node and the npm packages saved in your package.json file in the build
stages:
  - stage: build_adf
    displayName: Build ADF artifact
    jobs:
      - job: Creating
        displayName: "Creating Artifact"
        pool:
          vmImage: 'windows-latest'
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '14.x'
            displayName: 'Install Node.js'

          - task: Npm@1
            inputs:
              command: 'install'
              workingDir: '$(Build.Repository.LocalPath)/ADFIntegration' 
              verbose: true
            displayName: 'Install npm package'

# Validates all of the Data Factory resources in the repository. You'll get the same validation errors as when "Validate All" is selected.
# Enter the appropriate subscription and name for the source factory.

          - task: Npm@1
            inputs:
              command: 'custom'
              workingDir: '$(Build.Repository.LocalPath)/ADFIntegration' #package.json folder
              customCommand: 'run build validate $(Build.Repository.LocalPath)/ADFIntegration /subscriptions/$(resourcegroupid)/resourceGroups/$(resourcegroup)/providers/Microsoft.DataFactory/factories/$(adfname)'
            displayName: 'Validate'

# Validate and then generate the ARM template into the destination folder, which is the same as selecting "Publish" from the UX.
# The ARM template generated isn't published to the live version of the factory. Deployment should be done by using a CI/CD pipeline. 

          - task: Npm@1
            inputs:
              command: 'custom'
              workingDir: '$(Build.Repository.LocalPath)/ADFIntegration'
              customCommand: 'run build export $(Build.Repository.LocalPath)/ADFIntegration /subscriptions/$(resourcegroupid)/resourceGroups/$(resourcegroup)/providers/Microsoft.DataFactory/factories/$(adfname) ArmTemplate'  
            displayName: 'Validate and Generate ARM template'

# Publish the artifact to be used as a source for a release pipeline.
          - task: CopyFiles@2
            inputs:
              SourceFolder: '$(Build.Repository.LocalPath)/ADFIntegration/ArmTemplate'
              Contents: '**'
              TargetFolder: '$(build.artifactstagingdirectory)/application'
            displayName: 'Copying application artifact'


          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(build.artifactstagingdirectory)'
              artifact: 'datafactory'
              publishLocation: 'pipeline'

#release pipeline
  - stage: 'UAT'
    displayName: 'UAT deploy'
    dependsOn: build_adf
    variables:
      dataFactoryName: $(uat_datafactoryname)
  
    jobs:
      - deployment: DeploytoUAT
        pool:
          vmImage: 'windows-latest'
        environment: UAT
        strategy:
          runOnce:
            deploy:
              steps:
                - task: DownloadPipelineArtifact@2
                  inputs:
                    source: current
                    artifactName: 'ArmTemplates'
                    targetPath: '$(Pipeline.Workspace)'
                  displayName: Downloading Artifact
                - task: AzureResourceManagerTemplateDeployment@3
                  displayName: 'Deploying to UAT RG task'
                  inputs:
                    deploymentScope: Resource Group
                    azureResourceManagerConnection: $(myserviceconnection)
                    subscriptionId: $(subscriptionid)
                    action: Create Or Update Resource Group
                    resourceGroupName: $(rguatname)
                    location: $(UATlocation)
                    templateLocation: Linked artifact
                    csmFile: '$(Pipeline.Workspace)/datafactory/application/ARMTemplateForFactory.json'
                    csmParametersFile: '$(Pipeline.Workspace)/datafactory/application/ARMTemplateParametersForFactory.json'
                    overrideParameters: '-factoryName $(adfuatname) -dev_blob_linked_service_properties_typeProperties_connectionString_secretName $(UATsecretname) -AzureKeyVaultcode_properties_typeProperties_baseUrl $(UATkeyurl)'
                    deploymentMode: Incremental


                    
            
            


    